### ISSUE TITLE
json-schema.org Compatibility

### ISSUE THREAD

**Issue by skilledDeveloper** [Atinux/schema-inspector#17]
- When is it going to be compatible with json-schema.org? and will it be backward-compatible with v1.0?

In other words, if I integrate the current version into our application today, will I need to change our code once it becomes json-schema.org compatible?

**Comment by Atinux** [comment]
Hi @skilledDeveloper,

Actually, I don't have time to make the schema-inspector 100% compatible to json-schema.org.

If one day I'll do it, for sure, it's going to be another version (v2). I cannot say right now if it will be backward-compatible, it will depend on the difference between our logic and the json-schema.org logic.
