### ISSUE TITLE
Customizing and using validation output

### ISSUE THREAD

**Issue by spruce-bruce** [Atinux/schema-inspector#19]
Hi - I like the library. I've been having a hard time finding a good validation library to use in the browser so I really appreciate this.

There's one thing holding me back from using this in my project: I can't figure out how to customize my validation output so that I can easily pair errors to their fields in the markup.

This is some example code that produces validation errors:

```
var schema = {
    type : 'array',
    items : {
        type : 'object',
        properties : {
             foo : { type : 'string', minLength: 1}
        }
    }
};

var userInput = [
    {foo : 'bar'},
    {foo : ''},
    {foo : 'baz'}
];

var result = inspector.validate(schema, userInput);
console.log(result.error);
/*
[{
    message: "must be longer than 1 elements, but is has 0",
    property: "@[1].foo"
}]
*/
```

The property element on the error tells me exactly what I want to know: This error occurred on element 1 of the array, property foo. This, however, is a pain to parse programmatically without doing something crazy like using `eval`. Is there something I'm missing here? Do you guys have a suggestion on how to use this library to pair error messages with the fields where they originated in a complex form?

If not, can I suggest modifying the error output to mimic the schema more closely? I'd be willing to take a crack at putting a PR together if you're ok with error output like:

```
[
    null,
    { foo : {/*error message and code*/} },
    null
]
```

or:
```
[
    {
        type : array,
        index : 1,
        property : foo,
        message : '',
        code : ''
     }
]
```

**Comment by Atinux** [comment]
Hi!

Actually, I only used the library for the API, so the path displayed like that was more for a human reader.
But this seems to be a good idea.
I'm wondering what is the best way to do that. I think that the easiest way is your second proposition, but what about if the property is deeper in the object (property in an array which is in another property)?

I saw a JS library to get the actual property with the path given (https://github.com/mariocasciaro/object-path). Maybe it's easier to use it nope?

**Comment by Atinux** [comment]
With this library, you just have to change the value of property to remove the 2 first characters and all the "]", and replace "[" by a ".".

Example:
```js
'@[1].foo[0].bar[0]'.slice(2).replace(/\[/g, '.').replace(/\]/g, '')
// 1.foo.0.bar.0
```
