### ISSUE TITLE
Sanitization of an object to array

### ISSUE THREAD

**Issue by conradoqg** [Atinux/schema-inspector#22]
The example bellow works like a charm:
```
// Data
{
	tab: {
		prop: 'value'
	}
}

// Schema
{
	type: 'object',
	properties: {
		tab: {
			type: 'array',
			optional: false,
			def: [],
			items: { type: 'object' }
		}
	}
}

// Result
{
    "tab": [
        {
            "prop": "value"
        }
    ]
}
```
but, when the property is in the root of object, the sanitization do not work:
```
// Data
{
	prop: 'value'
}

// Schema
{
	type: 'array',
	optional: false,
	def: [],
	items: { type: 'object' }
}

// Result
{
	"prop": "value"
}
```

I was expecting this:
```
[{
	"prop": "value"
}]
```

This is useful when you are receiving a REST body that the data can be only one object or an array of objects.

Thank you.

**Comment by conradoqg** [comment]
Looking in the source `schema-inspection.js` and the specification, the 'candidate' is always passed as an object, so, even if the 'sanitize' function change their content from object to array, the change do not reflect to the variable.
Maybe the best way to deal with this, is to envelop with an object, the content to be sanitized and validated.

What do you think about that?

**Comment by Atinux** [comment]
Hi @conradoqg 

Thanks for using this module.
I understand, this is an issue of the schema-inspector. What do you think if I return the value of the sanitize function in result.data? Should it solve the problem?

**Comment by conradoqg** [comment]
Hi @Atinux !

I think it would solve.

Thank you!

**Comment by Atinux** [comment]
Alright, I'll do it tomorrow and push a new NPM version.
It's 1:25AM right now in Barcelona (Spain) so I have to sleep.

I'll close this issue when the module will be updated @conradoqg :+1:

**Comment by Atinux** [comment]
Hi @conradoqg 

It's updated, you can get the last version (1.5.5) and use it like that:
```javascript
var inspector = require('schema-inspector');

var schema = { type: 'array' };
var data = { prop: 'value' };

var result = inspector.sanitize(schema, c);
/*
    result.data will be equal to [{ prop: 'value' }]
*/
```

Thank you!
