### ISSUE TITLE
null or undefined default

### ISSUE THREAD

**Issue by martynsmith** [Atinux/schema-inspector#23]
This line of code means I can't have a default of `null` or `undefined`.

https://github.com/Atinux/schema-inspector/blob/master/lib/schema-inspector.js#L864

Is there any way I can do that? My goal is to declare an `integer` field, but in the case the input can't be parsed as an integer, I'd like the field to be `null` (rather than just passing through the invalid input).

**Comment by Atinux** [comment]
Hi @martynsmith 

I've just published the version 1.5.6 of the schema-inspector which fix this issue!

That was exactly the line you described that I had to change.

Here the test which is working now:
```js
test('candidate #5 | string -> integer or def: null', function () {
	var result = si.sanitize({ type: 'integer', def: null }, 'abc');
	result.should.be.an.Object;
	result.should.have.property('reporting').with.be.an.instanceof(Array).and.be.lengthOf(1);
	result.reporting[0].property.should.be.equal('@');
	should.equal(result.data, null);
});
```

Thank you!
