### ISSUE TITLE
minor issue : inconsistency between toObject and toArray sanitation

### ISSUE THREAD

**Issue by sebilasse** [Atinux/schema-inspector#24]
sanitize to array e.g. `"[javaScript, html,  css]"` ...

Basically string to object is like JSON.parse but string to array is not because the `[` and `]` are not "allowed".

For string toArray cast could you check if first char is  `[` and last is `]` and if so do JSON.parse which is what you use for to object as well ?

**Comment by Atinux** [comment]
Hi @sebilasse,

I merged your pull request + add a test for this feature + bumped the version to 1.5.8.

Thank you for your help!

**Comment by sebilasse** [comment]
:+1:
