### ISSUE TITLE
Avoid sanitization in some fields

### ISSUE THREAD

**Issue by YagoQuinoy** [Atinux/schema-inspector#27]
There is a way to avoid sanitization in some fields?

I'm interested on sanitization to parse date strings into date object(otherwise, validation fails), but at the same time i don't want to sanitize other fields. I want them to fail.

**Comment by Atinux** [comment]
Hi @YagoQuinoy 

Can you give me an example?

**Comment by YagoQuinoy** [comment]
Let's see this example:

```javascript
exports.index = function(req, res) {
  var parsedUrl = url.parse(req.url);
  var queryObj = queryString.parse(parsedUrl.query);
  var search = JSON.parse(queryObj.q);

  var sanitized = inspector.sanitize(searchSchema, search); // Example: ISODate Strings parsed into Date due to type sanitization.
  var result = inspector.validate(searchSchema, sanitized); // If more data is wrong, search is not valid.

  if (!result.valid) {
    console.log(result.format());
    return handleError(res, new Error('Very bad!'));
  }

  return res.status(200).json({
    message: 'Everything is fine'
  });
}
```

**Comment by YagoQuinoy** [comment]
I found a solution for tis example using the ['pattern'](https://github.com/Atinux/schema-inspector#pattern) option.

**Comment by Atinux** [comment]
Ok I see, what you can do is to use 2 different schemas, one for the sanitization and one for the validation. This is how I always do.

The pattern option is one solution too yes!

**Comment by YagoQuinoy** [comment]
That's a nice solution! It would be nice that you could add those kind of tips at the documentation.

**Comment by Atinux** [comment]
I will, than you @YagoQuinoy!
