### ISSUE TITLE
README.md#usage confusion

### ISSUE THREAD

**Issue by Nonemoticoner** [Atinux/schema-inspector#30]
https://github.com/Atinux/schema-inspector/blob/master/README.md#usage

The [readme](https://github.com/Atinux/schema-inspector/blob/master/README.md) is confusing imo. Neither *schema* nor *candidate* variables are existing in code snippet.
```js
var result = inspector.validate(schema, candidate);
```
Of course, I knew immediately what arguments should be given to *validate* function. Yet, I think this is an obvious bug and should be fixed in next release.

**Comment by Atinux** [comment]
Fixed thank you!
