### ISSUE TITLE
Invalid date is a correct Date, but...

### ISSUE THREAD

**Issue by Nonemoticoner** [Atinux/schema-inspector#31]
There should be some extra validation possibility for checking if Date object is valid e.g.:
```js
valid_date: {
    type: "date",
    isValid: true
}
```
That property *isValid* would be *false* by defaul of course.

http://stackoverflow.com/questions/1353684/detecting-an-invalid-date-date-instance-in-javascript

Remark: I tried to find such feature in the docs unsuccessfully. Maybe I simply didn't notice one. Sorry if that happened. Please, let me know then how to achieve such validation with use of this package.

**Comment by Atinux** [comment]
Hi @Nonemoticoner 

You can create a custom validator to check if a date is valid or no:
```js
var inspector = require('schema-inspector');
// Custom type schema
var customValidation = {
  validDate: function (schema, date) {
      if (schema.$validDate === true
         && Object.prototype.toString.call(date) === "[object Date]" 
         && isNaN(date.getTime())) {
          this.report('must be a valid date');
      }
  }
};
inspector.Validation.extend(customValidation);
```

This way, you can use this custom field at any validation, example:
```js
var data = {
	validDate: new Date(),
	invalidDate: new Date('invalid'),
	noDate: 'hello!'
};
var schema = {
	type: 'object',
	items: {
		type: 'date',
		$validDate: true
	}
};

var result = inspector.validate(schema, data);
console.log(result.format());
/*
Property @[invalidDate]: must be a valid date
Property @[noDate]: must be date, but is string
*/
```

**Comment by Nonemoticoner** [comment]
Oh, that's nice, thanks. I will add it to my project as solution for this problem I have coded by myself existed beyond the library so it was uglier ;)

Mainly, I meant this issue to introduce such property i.e. *validDate* as a preimplemented part of library - not just a plugin ;)

**Comment by Atinux** [comment]
Hi @Nonemoticoner 

I just pushed the version `1.6.2` with the `validDate: true` property.

Thanks for your suggestion :)

**Comment by Nonemoticoner** [comment]
That's great :)
