### ISSUE TITLE
'def' ignores 'optional'

### ISSUE THREAD

**Issue by Nonemoticoner** [Atinux/schema-inspector#32]
https://github.com/Atinux/schema-inspector#optional-1

The above snippet produces such value for _r.data_:

``` js
{ lorem: 12, ipsum: 23, dolor: 34 }
```

If we really wanted to achieve the _r.data_ equal to value as it's said in a comment, then the code should look like this:

``` js
var inspector = require('schema-inspector');

var schema = {
    type: 'object',
    properties: {
        lorem: { type: 'number', optional: false, def: 12 },
        ipsum: { type: 'string', optional: true },
        dolor: { type: 'string' } // (optional: true)
    }
};

var c = { };

var r = inspector.sanitize(schema, c);
/*
    r.data: {
        lorem: 12 // Only lorem is set to 12 because it is not optional.
    }
*/
```

I could PR that but I believe it's not how it should work in the end.

**Comment by Atinux** [comment]
HI @Nonemoticoner and sorry for the late answer

It's true, we don't want to create the property when they don't exist, only `optional: false` force the creation of the property.

Your PR is welcome to fix this issue!
