### ISSUE TITLE
URL validator does not consider `http://localhost` to be a valid URL

### ISSUE THREAD

**Issue by bjmiller** [Atinux/schema-inspector#33]
It looks like your URL validation regex is too strict.  It demands that there be at least one period in any hostname to be valid.  Systems that use local VPN-restricted DNS servers use names without any TLD by convention, and there are testing systems that need to use URLs such as `http://localhost:8000`.

**Comment by Atinux** [comment]
Hi Brian,

Thank you for your feedback, do you have any idea how to improve the Regex?

2015-12-21 20:46 GMT+01:00 Brian Miller <notifications@github.com>:

**Comment by bjmiller** [comment]
Apologies, I haven't had a chance to look at this yet.  I'll see what I can do soon.

**Comment by bjmiller** [comment]
For the URL regex:
If you change the `+` at position 501 to a `?`, it appears to create the correct behavior (Allowing domains without dots), without breaking any of the other behaviors.

That said, 1000+ character regexen are really challenging to maintain.  If you ever feel like taking another look at this, you might want to try something a little different.  Perhaps use a tool like Xregexp, which would let you spread the expression out over multiple lines and add comments, so that you can get some control over the complexity.

Would you like me to create a PR?  Or, would you prefer to make the change yourself?

**Comment by Atinux** [comment]
Hi @bjmiller 

Thanks for your suggestion, I want this module to be as much light as possible, so avoiding external libraries is optimal.

Of course your can do a pull request to fix the regex!
