### ISSUE TITLE
Problem with sanitize an array of objects

### ISSUE THREAD

**Issue by LucianoGanga** [Atinux/schema-inspector#36]
Hi! 

I'm trying to sanitize an array of objects with a custom function using exec, but when I run the sanitization, nothing happens. If I use the same function but outside the array of objects, it works perfectly.

This is my schema:
```javascript

var schema = {
	type: 'object',
	properties: {
		firstName: {
			type: 'string',
			rules: ['trim', 'title']
		},
		lastName: {
			type: 'string',
			rules: ['trim', 'title']
		},
		emails: {
			type: 'array',
			items: {
				address: {
					type: 'string',
					rules: ['trim', 'lower']
				}
			}
		},
		phones: {
			type: 'array',
			items: {
				number: {
					type: 'string',
					exec: function(schema, post) {
						return '+54' + post;
					}
				},
				type: {
					type: 'string'
				}
			}
		}
	}
};

```

Any ideas of what can be wrong?

Thanks!
Luciano

**Comment by Atinux** [comment]
Hi @LucianoGanga 

Your schema only sanitize the object properties it cannot work because you have to encapsulate it inside the array type:

```js
var schema = {
    type: 'array',
    items: {
        type: 'object',
        properties: {
            firstName: {
                type: 'string',
                rules: ['trim', 'title']
            },
            lastName: {
                type: 'string',
                rules: ['trim', 'title']
            },
            emails: {
                type: 'array',
                items: {
                    address: {
                        type: 'string',
                        rules: ['trim', 'lower']
                    }
                }
            },
            phones: {
                type: 'array',
                items: {
                    number: {
                        type: 'string',
                        exec: function(schema, post) {
                            return '+54' + post;
                        }
                    },
                    type: {
                        type: 'string'
                    }
                }
            }
        }
    }
};
```

Thank you for using schema-inspector :)

**Comment by LucianoGanga** [comment]
Hello @Atinux ! 

Thanks for your answer! :D 

The problem is that the array of objects that I was saying is not the full schema, it's only the "phones" property in the big object. Anyway, I tried your solution and it didn't work :(

Thanks anyway! 
I'm probably missing something here.

Cheers,
Luciano

**Comment by LucianoGanga** [comment]
I read again my original post and I notice that I wasn't so clear, sorry for the confusion!

**Comment by Atinux** [comment]
No problem @LucianoGanga 

Can you give me an example of your original data and what you expect in return?
This way I can help you to fix your sanitization schema :)

**Comment by LucianoGanga** [comment]
Sure! 

This is what I have: 

```javascript

{
	firstName: 'Alejandro',
	lastName: 'García',
	phones: [

		{
			number: '823155231918'
		}

	],
	emails: [

		{
			address: 'test@example.com'
		}

	]
}
```

And this is what I expect: 

```javascript

{
	firstName: 'Alejandro',
	lastName: 'García',
	phones: [

		{
			number: '+54 823155231918'
		}

	],
	emails: [

		{
			address: 'test@example.com'
		}

	]
}

```

**Comment by Atinux** [comment]
Hi, this is what I would do to sanitize your object:

```js
var schema = {
    type: 'object',
    properties: {
        firstName: {
            type: 'string',
            rules: ['trim', 'title']
        },
        lastName: {
            type: 'string',
            rules: ['trim', 'title']
        },
        emails: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    address: {
                        type: 'string',
                        rules: ['trim', 'lower']
                    }
                }
            }
        },
        phones: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    number: {
                        type: 'string',
                        exec: function(schema, post) {
                            return '+54' + post;
                        }
                    },
                    type: {
                        type: 'string'
                    }
                }
            }
        }
    }
};
```

As you can see, I added the type: 'object' inside your items for phones and emails.

**Comment by LucianoGanga** [comment]
Excellent!! It works perfectly now. I didn't know that I had to add the type explicitly there. 

Thanks @Atinux !! 
And have a nice day :) 

Luciano

**Comment by LucianoGanga** [comment]
One more question. If I run a validation instead of a sanitization... Do I have to declare explicitly the type of the content of the array? I mean, for the same schema. 

Thanks!
Luciano

**Comment by Atinux** [comment]
I'm not sure to understand, you're afraid that the validation will fail if you don't give an object in the phones property?

**Comment by LucianoGanga** [comment]
No no, I just meant that if I have to use the same schema structure that you told me when I write the schema for the validation, no for sanitization.

What I had before was this:
```javascript
{
...
phones: {
	type: 'array',
	items: {
		type: {
			type: 'string'
		},
		number: {
			type: 'string'
		},
		primary: {
			type: 'boolean'
		},
		mobile: {
			type: 'boolean'
		},
		enabled: {
			type: 'boolean'
		}
	},
...
}
```

Should I replace it with this?

```javascript
{
...
 phones: {
	type: 'array',
	items: {
		type: 'object',
		properties: {
			type: {
				type: 'string'
			},
			number: {
				type: 'string'
			},
			primary: {
				type: 'boolean'
			},
			mobile: {
				type: 'boolean'
			},
			enabled: {
				type: 'boolean'
			}
		}
	},
...
}
```

**Comment by Atinux** [comment]
Yes you have to use the second version, the sanitization and the validation have the same logic about the items property.

**Comment by LucianoGanga** [comment]
Perfect! Cheers @Atinux! 

And sorry for all the questions! 

From:  Sébastien Chopin
Reply-To:  Atinux/schema-inspector
Date:  Tuesday, February 16, 2016 at 5:17 PM
To:  Atinux/schema-inspector
Cc:  Luciano Ganga
Subject:  Re: [schema-inspector] Problem with sanitize an array of objects (#36)


Yes you have to use the second version, the sanitization and the validation have the same logic about the items property.

**Comment by Atinux** [comment]
Don't be sorry! I like to see that people find the scheme inspector useful :)
Thanks to you!
