### ISSUE TITLE
Meta-Schema

### ISSUE THREAD

**Issue by kwirke** [Atinux/schema-inspector#47]
Hello,

I have a project that uses Schema-Inspector schemas, but I have no way to detect at testing time if my schemas are valid, so I've been thinking on implementing a schema for validating Schema-Inspector schemas using Schema-Inspector itself. That is, a meta-schema.

So how do you feel it would be of use for this library? Could it be of any benefit? If that's the case, I can make you a pull request with the schema file added, though it would be independent from the code. I personally think it would be best to have all schemas passed down to `validate` and `sanitize` validated against the meta-schema, but I don't have the time to go into the code.

Also, it would be very helpful if someone else has started this endeavour before and can provide any help.

I'll appreciate your thoughts on this. Thank you for this library,
Regards.

**Comment by Atinux** [comment]
Hi @kwirke, it's indeed a good idea but I don't think it would be good to have it inside the library (making it heavier).

Maybe adding it on the website to help the people to validate their schemes?

Thank you @kwirke
