### ISSUE TITLE
A way to send parameter to custom fields

### ISSUE THREAD

**Issue by xgvargas** [Atinux/schema-inspector#48]
I'm trying to use schema-inspector to validate an object in an express api. Something like this:

```coffee
inspector = require 'schema-inspector'

custom =
    unique: (schema, candidate, cb) ->
        # need to use mongo connection in here!

inspector.Validation.extend custom

schema =
    type: 'object'
    properties:
        name: {type: 'string', $unique: true}

# app == express()
app.use (req, res, next) ->
    req.conn = getMongoConnectionFromCachedConnections(req.jwt)
    next()

app.post '/resource', (req, res) ->

    # here I need to send req.conn to validate function...
    v = inspector.validate schema, req.body
    if v.valid
        req.conn.insert req.body
```
Inside first middleware I'm checking a `jwt` token that tells me what DB this post should affect.

In following middlewares I use this connection to touch database. But for my validation I need to check DB to see if `name` is unique (allowed), ou already in there.

How can I let my validator code receive the connection it needs?

**Comment by Atinux** [comment]
Hi @xgvargas 

There is a tricky way by using `this.origin` in your `unique` method:
```js
custom =
    unique: (schema, candidate, cb) ->
      console.log(this.origin._conn)
      cb()
```

And then you can surcharge the req.body by adding the _conn:
```js
app.post('/resource', function (req, res) {
  req.body._conn = req.conn;
  inspector.validate(schema, req.body, function (err, v) {
    delete req.body._conn
    if (v && v.valid) {
      req.conn.insert(req.body);
    }
  });
});
```

**Comment by xgvargas** [comment]
@atinux, thanks, this works :smile:. I'm sad I haven't thought about that approach.

But it causes an error when schema has `strict=true`, since `_conn` is not allowed in this case. I solved by accepting doc when this is the only error. It would be nice if was possible to have a more official way to accomplish that.
