### ISSUE TITLE
Mutual exclusive properties?

### ISSUE THREAD

**Issue by heycalmdown** [Atinux/schema-inspector#50]
Recently I'm looking Telegram Bot API which is plain REST APIs. There is a some point that attract me, it's rare, but reasonable limitation of API schema.

https://core.telegram.org/bots/api/#inlinekeyboardbutton

The document says 

> You must use exactly one of the optional fields.

Which means, if you set a property of the API, then you can't set the others. It's kind of a mutual exclusive. Could `schema-inspector` model this?

**Comment by Atinux** [comment]
Hi @heycalmdown 

You can extend the schema-inspector to allow this behaviour.

```js
var schema = {
    type: 'object',
    exec: function (schema, post) {
          // here you can check the root object post and check if only 1 key is available here
    }
};
```

Hope it helps!
