### ISSUE TITLE
Need Roadmap

### ISSUE THREAD

**Issue by anubhavsrivastava** [Atinux/schema-inspector#52]
Provide roadmap for both sanitize and validation part
- support for es6+ data types
- additional validation types
- promise support

**Comment by Atinux** [comment]
I was also thinking about merging the sanitization and validation together.

Would like to know some feedback about it.

What are the es6+ data types you're thinking of?

**Comment by anubhavsrivastava** [comment]
Map and Set basically.

use cases: on back-end js, set needs both sanitization and validation. 
`any` doesn't fulfill the case.

ES6+ support will break code on already existing client codebase. Something in form of plugins/extensions would help.
