### ISSUE TITLE
to array form confusing

### ISSUE THREAD

**Issue by heycalmdown** [Atinux/schema-inspector#53]
Let's say we have this sanitization form

```javascript
{
	"type":"object",
	"properties":{
		"code":{
			"type":"array",
			"items":{
				"type":"number"
			}
		},
		"class":{
			"type":"array",
			"items":{
				"type":"string"
			}
		}
	}
}
```

When I send body like below, the result looks reasonable.

```javascript
// source
{ code: '2,4,6', class: 'C,A' }
// -> result
{ code: [2,4,6], class: ['C', 'A'] }
```

However, look this situation,

```javascript
// source
{ code: '[2,4,6]', class: '[C,A]' }
// -> result
{ code: [2,4,6], class: '[C,A]' }
```

numbers go right, but strings are not. The source is not weird form while we are dealing with query params like `?code=[2,4,6]&class=[C,A]`. Because everything are strings in query params as you know.

**Comment by Atinux** [comment]
Hi @heycalmdown 

When the value is "[C,A]", schema-inspector call JSON.parse(), and it fails because it's not a valid JSON string. On the other hand, "[2,4,6]" can be parsed via JSON.parse()

You should try to send ?code=2,4,6&class=C,A or ?code=[2,4,6]&class=["C","A"]

**Comment by heycalmdown** [comment]
Got it. I understood. Thanks! :)
