### ISSUE TITLE
Email validation with pattern: email

### ISSUE THREAD

**Issue by coolstunt** [Atinux/schema-inspector#57]
Using version 1.6.6 and Email validation with pattern: 'email' is not validating the emails with certain formats

Ex: cool@simple.c is passed the validation. But .c is not a valid tld for now.
Can you please let me know if this is fixed in later releases.

**Comment by Telokis** [comment]
Your specific case is a valid email. This kind of verification (is it a real email?) is done by sending a confirmation email to the user. The pattern is correct *in se*.

**Comment by Atinux** [comment]
Any PR is welcome to improve the email regexp :)
