### ISSUE TITLE
exec/customValidator, set error reason?

### ISSUE THREAD

**Issue by mbt-jeremy-r** [Atinux/schema-inspector#59]
Is there a way to set the error reason in customValidator or in a exec validation?

From the documentation and [#31](https://github.com/Atinux/schema-inspector/issues/31), I can only set the message with `this.report`.

**Comment by Atinux** [comment]
Hi @mbt-jeremy-r 

Sorry it's not in the documentation but as you can see here: https://github.com/Atinux/schema-inspector/blob/master/lib/schema-inspector.js#L584

You can define a custom error code as the 2nd argument and the reason as 3rd argument of `this.report(message [, code] [, reason])`
