### ISSUE TITLE
def in sanitization doesn't work

### ISSUE THREAD

**Issue by D219** [Atinux/schema-inspector#60]
Tested on [the live version](https://atinux.fr/schema-inspector/)

Data:

    {}

Sanitization:

    {
        type: "object",
        strict: true,
        properties: {
            test: {
                type: "array",
                def: []
            }
        }
    }

No validation.

Result in:

    {}

I was expecting `def` to catch on and add the `test` property:

    {
        test: []
    }

Is it me that misread the documentation, or is sanitization not working when the field is not set at all?

**Comment by Telokis** [comment]
From [the sanitization doc](https://github.com/Atinux/schema-inspector#s_optional), the property `optional` is `true` by default. Setting it to `false` in your example produces the expected result.

```
{
    type: "object",
    strict: true,
    properties: {
        test: {
            type: "array",
            def: [],
            optional: false
        }
    }
}
```

Generated

```
{
    "test": []
}
```
