### ISSUE TITLE
jquery 2.0.3 has known vulnerabilities

### ISSUE THREAD

**Issue by nancruz** [Atinux/schema-inspector#63]
You have a dependency on jquery 2.0.3 which has known vulnerabilities: https://github.com/jquery/jquery/issues/2432 

You should consider upgrading from version 2.x to version 3.x, since 2.x is no longer supported and doesn't not have a fix for the known vulnerabilities.

Offtopic: Why are you depending on jquery?

**Comment by bkniffler** [comment]
I'm not sure where you see jquery dependency?

**Comment by nancruz** [comment]
In fact you are not depending on jquery. However, you have a jquery lib under the misc folder, which marks this library as non-secure. 
I'm just saying that you should update that lib in order to avoid having your lib marked as non-secure.

**Comment by bkniffler** [comment]
Ah, didn't know about that.. I'm not the maintainer btw :)

**Comment by mattwelke** [comment]
Solved with https://github.com/Atinux/schema-inspector/pull/81.
