### ISSUE TITLE
Feat Request: type Enum

### ISSUE THREAD

**Issue by GeorgeWL** [Atinux/schema-inspector#72]
I can see it as being rather helpful, the idea being where you want a string, but you only want one of a select set.

An example use case, a database connected to an api expects only one of a set of values for a status field, but as this is more than 3, using boolean doesn't work.

So they could validate it with the enum of a object containing expected strings.

**Comment by LeoFalco** [comment]
Hello @GeorgeWL,

You can use a validator using eq and a array of accepted values

like this:

data: 
```js
{ 
  language: "JAVA"
}
```

validation schema:
```js
{
  type: "object",
  properties: {
    language: {
      type: "string", eq:['JAVASCRIPT', 'HTML','CSS']
    },
  }
}
```

result:
```
Validation error:
Property @.language: must be equal to ["JAVASCRIPT" or "HTML" or "CSS"], but is equal to "JAVA"
```

**Comment by GeorgeWL** [comment]
Ah, awesome, thanks for that.

**Comment by mattwelke** [comment]
Closing because feature already exists.
