### ISSUE TITLE
Vulnerabilities and outdated dependencies

### ISSUE THREAD

**Issue by JiunHong** [Atinux/schema-inspector#73]
Can we get the dependencies updated for this as well as the JQuery in the misc folder to be updated? Code scans is throwing a lot of errors for this. Thank you!

**Comment by mattwelke** [comment]
Fixed with https://github.com/Atinux/schema-inspector/pull/81.

Note that async@2.x is still supported (in addition to their 3.x) and we're pinned to it for now to maintain IE support.
