### ISSUE TITLE
[ NSFW] Live example doesn't look like live example any more...

### ISSUE THREAD

**Issue by piotrekfracek** [Atinux/schema-inspector#74]
It seems that http://atinux.github.io/schema-inspector/ redirects to some kind of porn site.

**Comment by eaharonoff** [comment]
Embarrassingly opened that link at work before I saw this issue 🤦‍♂️

**Comment by theadamfarah** [comment]
I opened this up while on a shared screen conference call. We all had a good laugh at my expense. Could have easily gone the other way though...

**Comment by eaharonoff** [comment]
doesn't look like this is being maintained anymore :(

**Comment by mattwelke** [comment]
Closing because not reproducible. Looks like GitHub may have had a DNS issue at one point in time.
