### ISSUE TITLE
A vulnerability in validate()

### ISSUE THREAD

**Issue by xiaofen9** [Atinux/schema-inspector#76]
we found a vulnerability in validate() which might allow malicious attackers bypass validation.
This vulnerability is very similiar to this issue https://github.com/Atinux/schema-inspector/issues/75 

https://github.com/Atinux/schema-inspector/blob/7f67b2a95f85ecb76d0dc5326d76d082a2b99e1f/lib/schema-inspector.js#L483

**Comment by Atinux** [comment]
It's now fixed in https://github.com/Atinux/schema-inspector/releases/tag/v1.6.9, thank you <3
